### ISSUE TITLE
1.17 Sword Blocking mod is doesn't working

### ISSUE THREAD

**Issue by MisileLab** [TeamMidnightDust/SwordBlocking#3]
Minecraft crashing when loading mod.

**Comment by LimesKey** [comment]
Im getting this error The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'swordblocking'!
Exit Code: -1.

while running latest verison of fabric with fabric api + optifabric + optifine and some other small other mods that shouldnt affect it..

**Comment by LimesKey** [comment]
more info:

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'swordblocking'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.NoSuchMethodError: 'void net.fabricmc.fabric.api.object.builder.v1.client.model.FabricModelPredicateProviderRegistry.register(net.minecraft.class_1792, net.minecraft.class_2960, net.minecraft.class_1800)'
	at eu.midnightdust.swordblocking.SwordBlockingClient.lambda$onInitializeClient$1(SwordBlockingClient.java:16)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at eu.midnightdust.swordblocking.SwordBlockingClient.onInitializeClient(SwordBlockingClient.java:14)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more

**Comment by Motschen** [comment]
Please try this version: https://github.com/helpimnotdrowning/SwordBlocking/releases/tag/v1.1.0
If it works fine, I'll push the build on CF and Modrinth

**Comment by barraIhsan** [comment]
> Please try this version: https://github.com/helpimnotdrowning/SwordBlocking/releases/tag/v1.1.0
> If it works fine, I'll push the build on CF and Modrinth

Yep, its doesn't crash

**Comment by MrAn0nym** [comment]
> Please try this version: https://github.com/helpimnotdrowning/SwordBlocking/releases/tag/v1.1.0 If it works fine, I'll push the build on CF and Modrinth

Is it already up?

**Comment by Motschen** [comment]
yes, it is
